// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asxxotyratempbuxetma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzeHhvdHlyYXRlbXBidXhldG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0OTM5MDcsImV4cCI6MjA2OTA2OTkwN30.E1Ouzgr22uzPhF2QsiXqKbv9vVhqhC8bDM7BK2RyFfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});